# -*- coding: utf-8 -*-"

rebasedb = 'rebase53.db'
upstreamdb = 'upstream53.db'
nextdb = 'next53.db'

rebase_baseline_branch = 'chromeos-4.19'
android_baseline_branch = "android-4.19"

android_site = "https://android.googlesource.com/"
kernel_site = "https://git.kernel.org/"
chromium_site = "https://chromium.googlesource.com/"

android_repo = android_site + "kernel/common"
next_repo = kernel_site + "pub/scm/linux/kernel/git/next/linux-next"
upstream_repo = kernel_site + "pub/scm/linux/kernel/git/torvalds/linux"
stable_repo = kernel_site + "pub/scm/linux/kernel/git/stable/linux-stable"
chromeos_repo = chromium_site + "chromiumos/third_party/kernel"

rebase_baseline = 'v4.19'
stable_baseline = 'v4.19.73'
rebase_target = 'v5.3'

chromeos_path = "linux-chrome"
stable_path = "linux-stable"
android_path = "linux-android"
upstream_path = "linux-upstream"
next_path = "linux-next"

# Clear subject_droplist as follows to keep andoid patches
# subject_droplist = []
subject_droplist = ["ANDROID:", "Android:", "android:"]

droplist = [('drivers/net/wireless/iwl7000', 'Intel'),
#           ('drivers/gpu/drm/i915', 'Intel'),
#           ('drivers/gpu/drm/amd', 'AMD')
	    ]

topiclist = \
    [["chromeos",
      ["chromeos", "COMMIT-QUEUE.ini", "PRESUBMIT.cfg"]],
     ["cros_ec/iio",
      ["drivers/iio/common/cros_ec_sensors",
       "drivers/iio/accel/cros_ec_accel_legacy.c",
       "drivers/iio/pressure/cros_ec_baro.c",
       "drivers/iio/counter/cros_ec_sensors_sync.c",
       "drivers/iio/light/cros_ec_light_prox.c",
       "include/linux/iio/common/cros_ec_sensors_core.h" ]],
     ["cros_ec/wilco",
      [ "drivers/platform/chrome/wilco_ec", "drivers/rtc/rtc-wilco-ec",
      "drivers/power/supply/wilco-charger",
      "include/linux/platform_data/wilco-ec.h",
      "Documentation/ABI/testing/debugfs-wilco-ec",
      "Documentation/ABI/testing/sysfs-platform-wilco-ec" ]],
     ["cros_ec",
      ["drivers/extcon/extcon-usbc-cros_ec",
       "Documentation/devicetree/bindings/extcon/extcon-cros-ec.txt",
       "drivers/mfd/cros_ec", "drivers/power/cros",
       "drivers/rtc/rtc-cros-ec", "drivers/platform/chrome",
       "drivers/platform/x86/chrome", "drivers/platform/arm/chrome",
       "drivers/input/keyboard/cros_ec",
       "drivers/pwm/pwm-cros-ec.c",
       "drivers/regulator/cros_ec",
       "drivers/i2c/busses/i2c-cros-ec", "include/linux/mfd/cros_ec",
       "include/linux/chromeos",
       "Documentation/devicetree/bindings/chrome"]],
     ["power",
      ["drivers/power", "drivers/base/power", "kernel/power",
       "include/dt-bindings/power", "include/linux/power",
       "include/linux/pm", "Documentation/power", "arch/x86/power",
       "Documentation/devicetree/bindings/power"]],
     ["usb-gadget",
      ["drivers/usb/gadget"]],
     ["usb",
      ["drivers/usb", "include/linux/usb", "include/uapi/linux/usb",
       "Documentation/devicetree/bindings/usb",
       "tools/usb"]],
     ["arm/mali",
      ["drivers/gpu/arm"]],
     ["drm/amd",
      ["drivers/gpu/drm/amd"]],
     ["drm/i915",
      ["drivers/gpu/drm/i915"]],
     ["drm/mediatek",
      ["drivers/gpu/drm/mediatek"]],
     ["drm/qualcomm",
      ["drivers/gpu/drm/msm"]],
     ["drm/panel",
      ["drivers/gpu/drm/panel"]],
     ["drm/rockchip",
      ["drivers/gpu/drm/rockchip"]],
     ["drm/virtio",
      ["drivers/gpu/drm/virtio", "include/drm/virtio_drm.h"]],
     ["gpu/other",
      ["drm", "drivers/gpu", "include/drm", "Documentation/devicetree/bindings/drm",
       "include/uapi/drm"]],
     ["media",
      ["drivers/media", "include/media", "include/uapi/linux/videodev2.h",
       "include/uapi/linux/v4l2-controls.h", "Documentation/media" ]],
     ["input",
      ["drivers/input", "include/linux/input"]],
     ["iio",
      ["drivers/iio", "drivers/staging/iio", "Documentation/driver-api/iio",
       "Documentation/devicetree/bindings/iio",
       "Documentation/devicetree/bindings/staging/iio",
       "Documentation/iio", "include/linux/iio", "include/uapi/linux/iio",
       "include/dt-bindings/iio"]],
     ["mmc",
      ["drivers/mmc", "Documentation/mmc", "include/linux/mmc",
       "include/uapi/linux/mmc"]],
     ["mtd",
      ["drivers/mtd", "include/linux/mtd", "include/uapi/mtd",
       "Documentation/mtd", "Documentation/devicetree/bindings/mtd"]],
     ["bluetooth",
      ["net/bluetooth", "drivers/bluetooth",
       "Documentation/devicetree/bindings/net/btusb.txt",
       "include/net/bluetooth"]],
     ["wireless",
      ["net/wireless", "drivers/net/wireless",
       "Documentation/devicetree/bindings/net/wireless"]],
     ["net",
      ["drivers/net/usb", "net", "drivers/net", "include/linux/tcp.h",
       "include/uapi/linux/tcp.h",
       "include/net", "include/dt-bindings/net", "include/linux/net",
       "include/uapi/linux/sockios.h"]],
     ["sound/intel",
      ["sound/soc/intel"]],
     ["sound/mediatek",
      ["sound/soc/mediatek"]],
     ["sound/rockchip",
      ["sound/soc/rockchip"]],
     ["sound/other",
      ["sound", "Documentation/devicetree/bindings/sound", "include/sound",
       "include/uapi/sound"]],
     ["security",
      ["security", "include/linux/alt-syscall.h", "include/linux/syscalls.h",
       "arch/arm64/kernel/alt-syscall.c",
       "arch/x86/kernel/alt-syscall.c", "kernel/alt-syscall.ch"]],
     ["android",
      ["android", "Documentation/android", "drivers/android",
       "drivers/staging/android",
       "include/linux/android", "include/uapi/linux/android"]],
     ["fs/pstore",
      ["fs/pstore", "include/linux/pstore",
       "Documentation/devicetree/bindings/reserved-memory/ramoops.txt",
       "Documentation/devicetree/bindings/misc/ramoops.txt",
       "Documentation/ramoops.txt"]],
     ["fs/ecryptfs",
      ["fs/ecryptfs"]],
     ["fs/esdfs",
      ["fs/esdfs"]],
     ["fs/other",
      ["fs"]],
     ["hid",
      ["drivers/hid"]],
     ["md",
      ["drivers/md", "init/do_mounts_dm.c", "Documentation/device-mapper/boot.txt"]],
     ["thermal",
      ["drivers/thermal", "include/linux/thermal",
       "Documentation/devicetree/bindings/thermal"]],
     ["regulator",
      ["Documentation/devicetree/bindings/regulator", "drivers/regulator",
      "include/linux/regulator"]],
     ["scsi",
      ["drivers/scsi"]],
     ["virtio",
      ["drivers/virtio", "include/uapi/linux/virtwl.h"]],
     ["sysrq",
      ["drivers/tty/sysrq.c"]],
     ["firmware/google",
      ["drivers/firmware/google"]],
     ["tpm",
      ["drivers/char/tpm", "Documentation/devicetree/bindings/security/tpm"]],
     ["lowmem",
      ["include/linux/low-mem-notify.h", "mm/low-mem-notify.c",
       "tools/mm/low-mem-test.c", "drivers/char/mem.c"]],
     ["mm",
      ["mm", "include/linux/mm_metrics.h", "include/linux/swapops.h"]],
     ["scheduler",
      ["include/linux/sched", "kernel/sched"]],
     ["cgroup",
      ["kernel/cgroup"]],
     ["dts/qcom",
      ["arch/arm64/boot/dts/qcom"]],
     ["dts/mediatek",
      ["arch/arm64/boot/dts/mediatek",
       "Documentation/devicetree/bindings/display/mediatek",
       "Documentation/devicetree/bindings/soc/mediatek",
       "Documentation/devicetree/bindings/arm/mediatek"
      ]],
     ["dts/rk3399",
      ["arch/arm64/boot/dts/rockchip"]],
     ["dts/arm",
      ["arch/arm/boot/dts"]],
     ["acpi",
      ["drivers/acpi"]],
     ["container/arm64",
      ["arch/arm64/configs/chromiumos-container-vm-arm64_defconfig"]],
     ["container/x86",
      ["arch/x86/configs/chromiumos-container-vm-x86_64_defconfig",
       "arch/x86/configs/x86_64_arcvm_defconfig"]],
     ["drivers/mediatek",
      ["drivers/clk/mediatek",
       "drivers/pinctrl/mediatek",
       "drivers/soc/mediatek"
      ]],
     ["drivers/rockchip",
      ["drivers/clk/rockchip",
       "drivers/soc/rockchip",
       "drivers/crypto/rockchip",
       "drivers/clk/rockchip"
      ]],
     ["cpufreq",
      ["drivers/cpufreq"]],
     ["devfreq",
      ["drivers/devfreq"]],
     ["iommu",
      ["drivers/iommu"]],
     ["mfd",
      ["drivers/mfd"]],
     ["arch/arm",
      ["arch/arm"]],
     ["arch/arm64",
      ["arch/arm64"]],
     ["arch/x86",
      ["arch/x86"]],
     ["devicetree",
      ["Documentation/devicetree"]],
    ]
