patchlist = "patchlist-3584f61144fd"

rebasedb = 'rebase49.db'
upstreamdb = 'upstream49.db'

rebase_baseline = 'v4.4'
stable_baseline = 'v4.4.52'
rebase_target = 'v4.9'

chromeos_path = "linux-chrome"
stable_path = "linux-stable"
android_path = "linux-android"
upstream_path = "linux-upstream"

droplist = [ ("drivers/net/wireless/iwl7000", "intel"),
	( "include/config/iwl7000", "intel" ),
	( "drivers/gpu/drm/i915", "intel" ),
	( "drivers/gpu/drm/mediatek", "mediatek" ),
	( "drivers/thermal/mtk_thermal", "mediatek" ),
	( "drivers/clk/mediatek", "mediatek" ),
	( "drivers/soc/mediatek", "mediatek" ),
	( "drivers/media/platform/mtk", "mediatek" ),
	( "Documentation/devicetree/bindings/media/mediatek", "mediatek" ),
	( "Documentation/devicetree/bindings/soc/mediatek", "mediatek" ),
	( "sound/soc/mediatek", "mediatek" ),
	( "sound/soc/intel", "intel" ),
	( "drivers/cpufreq/mt8173", "mediatek" ),
	( "arch/arm64/boot/dts/mediatek", "mediatek" ),
	( "drivers/net/wireless/ar10k", "atheros" ),
	( "drivers/gpu/drm/img-rogue", "imgtec" )
	]

topics = [ ("chromeos", 1),
	("COMMIT-QUEUE.ini", 1),
	("PRESUBMIT.cfg", 1),
	("drivers/extcon/extcon-cros_ec", 2),
	("Documentation/devicetree/bindings/extcon/extcon-cros-ec.txt", 2),
	("drivers/mfd/cros_ec", 2),
	("drivers/power/cros", 2),
	("drivers/rtc/rtc-cros-ec", 2),
	("drivers/platform/chrome", 2),
	("drivers/platform/x86/chrome", 2),
	("drivers/platform/arm/chrome", 2),
	("drivers/input/keyboard/cros_ec", 2),
	("drivers/pwm/pwm-cros-ec.c", 2),
	("drivers/iio/common/cros_ec_sensors", 2),
	("drivers/regulator/cros_ec", 2),
	("drivers/i2c/busses/i2c-cros-ec", 2),
	("include/linux/mfd/cros_ec", 2),
	("include/linux/chromeos", 2),
	("Documentation/devicetree/bindings/chrome", 2),
	("arch/arm64/boot/dts/rockchip", 3),
	("arch/arm/boot/dts/rockchip", 3),
	("arch/arm/boot/dts/rk3", 3),
	("drivers/devfreq/rk3399", 4),
	("drivers/devfreq/event/rockchip", 4),
	("drivers/clk/rockchip", 5),
	("include/dt-bindings/clock/rk3399", 5),
	("drivers/spi/spi-rockchip", 6),
	("drivers/phy/phy-rockchip", 7),
	("Documentation/devicetree/bindings/phy/phy-rockchip", 7),
	("drivers/usb/dwc3/dwc3-rockchip", 8),
	("drivers/crypto/rockchip", 9),
	("drivers/gpu/drm/rockchip", 10),
	("drivers/gpu/drm/bridge/analogix", 10),
	("include/drm/bridge/analogix_dp.h", 10),
	("Documentation/devicetree/bindings/display/rockchip", 10),
	("drivers/media/platform/rockchip-vpu", 10),
	("drivers/media/platform/rk3288", 10),
	("Documentation/devicetree/bindings/display/rockchip/analogix_dp-rockchip.txt", 10),
	("drivers/gpu/arm/midgard", 10),
	("include/soc/rockchip", 11),
	("sound/soc/rockchip", 11),
	("drivers/soc/rockchip", 11),
	("Documentation/devicetree/bindings/sound/rockchip", 11),
	("arch/arm/mach-rockchip", 11),
	("include/dt-bindings/power/rk3399", 12),
	("Documentation/devicetree/bindings/pci/rockchip", 14),
	("drivers/pci/host/pcie-rockchip", 14),
	("drivers/thermal/rockchip", 15),
	("drivers/iommu/rockchip", 16),
	("drivers/power", 20),
	("drivers/base/power", 20),
	("kernel/power", 20),
	("include/dt-bindings/power", 20),
	("include/linux/power", 20),
	("include/linux/pm", 20),
	("Documentation/power", 20),
	("arch/x86/power", 20),
	("Documentation/devicetree/bindings/power", 20),
	("drivers/usb", 21),
	("include/linux/usb", 21),
	("include/uapi/linux/usb", 21),
	("Documentation/devicetree/bindings/usb", 21),
	("drivers/gpu", 22),
	("include/drm", 22),
	("Documentation/devicetree/bindings/drm", 22),
	("include/uapi/drm", 22),
	("drivers/media", 23),
	("include/media", 23),
	("include/uapi/linux/videodev2.h", 23),
	("include/uapi/linux/v4l2-controls.h", 23),
	("drivers/input/touchscreen/atmel_mxt_ts.c", 24),
	("include/linux/platform_data/atmel_mxt_ts.h", 24),
	("drivers/input", 25),
	("include/linux/input", 25),
	("drivers/iio", 26),
	("drivers/staging/iio", 26),
	("Documentation/driver-api/iio", 26),
	("Documentation/devicetree/bindings/iio", 26),
	("Documentation/devicetree/bindings/staging/iio", 26),
	("Documentation/iio", 26),
	("include/linux/iio", 26),
	("include/uapi/linux/iio", 26),
	("include/dt-bindings/iio", 26),
	("drivers/mmc", 27),
	("Documentation/mmc", 27),
	("include/linux/mmc", 27),
	("include/uapi/linux/mmc", 27),
	("drivers/mtd", 28),
	("include/linux/mtd", 28),
	("include/uapi/mtd", 28),
	("Documentation/mtd", 28),
	("Documentation/devicetree/bindings/mtd", 28),
	("net/bluetooth", 29),
	("drivers/bluetooth", 29),
	("Documentation/devicetree/bindings/net/btusb.txt", 29),
	("include/net/bluetooth", 29),
	("net/wireless", 30),
	("drivers/net/wireless", 30),
	("Documentation/devicetree/bindings/net/wireless", 30),
	("drivers/net/usb", 31),
	("net", 31),
	("drivers/net", 31),
	("include/linux/tcp.h", 31),
	("include/uapi/linux/tcp.h", 31),
	("include/net", 31),
	("include/dt-bindings/net", 31),
	("include/linux/net", 31),
	("include/uapi/linux/sockios.h", 31),
	("sound", 32),
	("Documentation/devicetree/bindings/sound", 32),
	("include/sound", 32),
	("include/uapi/sound", 32),
	("security", 33),
	("include/linux/alt-syscall.h", 33),
	("arch/arm64/kernel/alt-syscall.c", 33),
	("arch/x86/kernel/alt-syscall.c", 33),
	("kernel/alt-syscall.ch", 33),
	("android", 34),
	("Documentation/android", 34),
	("drivers/android", 34),
	("drivers/staging/android", 34),
	("include/linux/android", 34),
	("include/uapi/linux/android", 34),
	("fs/pstore", 35),
	("include/linux/pstore", 35),
	("Documentation/devicetree/bindings/reserved-memory/ramoops.txt", 35),
	("Documentation/devicetree/bindings/misc/ramoops.txt", 35),
	("Documentation/ramoops.txt", 35),
	("fs", 36),
	("drivers/hid", 36),
	("drivers/thermal", 37),
	("include/linux/thermal", 37),
	("Documentation/devicetree/bindings/thermal", 37),
	("Documentation/devicetree/bindings/regulator", 38),
	("drivers/regulator", 38),
	("include/linux/regulator", 38),
	("drivers/scsi", 39),
	("drivers/firmware/google", 40),
	("drivers/char/tpm", 41),
	("Documentation/devicetree/bindings/security/tpm", 41)
	]
